spring:
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    generate-ddl: false

  sql:
    init:
      data-locations: classpath*:db/mysql/data.sql
      schema-locations: classpath*:db/mysql/schema.sql
      mode: always

  datasource:
    password:
    url:
    username:
    driver-class-name:

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

jwt:
  access-token-expiration-minutes:
  refresh-token-expiration-minutes:
  key:
    secret:

mail:
  address:
    admin: