spring:
  datasource:
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    url: ${RDS_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      data-locations:
        - classpath*:db/mysql/data.sql
      encoding: UTF-8
      mode: always

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

jwt:
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
  key:
    secret: ${JWT_SECRET_KEY}

mail:
  address:
    admin: ${ADMIN_EMAIL}

api:
  ai:
    key: ${OPEN_AI_KEY}