spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

jwt:
  access-token-expiration-minutes: 59
  refresh-token-expiration-minutes: 420
  key:
    secret: sdkfsdklfjskldfnfkjerfhqjkwhejkasndjkansjkdflkjasdhfljkhdsjkdhsfjkslvkjasdnlkjndslkfnlsadnfsdfsadf

mail:
  address:
    admin: zl@dfl.com

api:
  ai:
    key: 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