spring:
  jpa:
    hibernate:
      ddl-auto: create
    #defer-datasource-initialization: true

  datasource:
    password: seb39main1
    url: jdbc:mysql://database-3.cn22higluw0t.ap-northeast-2.rds.amazonaws.com:13306/test
    username: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always


logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

jwt:
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 420
  key:
    secret: noterrorvegetarian7894431123412341234qwerjameshongyunAAgErt

mail:
  address:
    admin: admin056@admin.com