spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

jwt:
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 420
  key:
    secret: noterrorvegetarian7894431123412341234qwerjameshongyunAAgErt

mail:
  address:
    admin: admin056@admin.com